### ISSUE TITLE
Keep tags naming consistent

### ISSUE THREAD

**Issue by licaon-kter** [pretix/pretixscan-android#10]
..else F-Droid can't autoupdate

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6428/diffs#diff-content-0fea63baa1ec1efe202dd609e3645937d9588aca

**Comment by raphaelm** [comment]
Apparently, 1.2.3/4 were inconsistent, I'm sorry, but 1.2.5 is already correct again. This happens when switchting between different projects a lot, I'll try to be careful :man_shrugging:
