### ISSUE TITLE
Display question detail during scan

### ISSUE THREAD

**Issue by camlafit** [pretix/pretixscan-android#120]
Hello

I've not found any option to display question related to an item.
In our use case we ask to our visitor if an access help is required or if a specific food must applied to their lunch. 

During scan, display these informations could be useful to improve reception experience for these people. 

Have a nice day

**Comment by raphaelm** [comment]
There's an option for it in the advanced question settings:

![image](https://github.com/user-attachments/assets/3ad72d8a-09ad-427e-8197-1ba3af1f9e2e)

**Comment by camlafit** [comment]
Thank a lot :)
