### ISSUE TITLE
Security error while trying to reach the server

### ISSUE THREAD

**Issue by sborja** [pretix/pretixscan-android#15]
I have al self hosted installation of pretix, but i have a problem trying to connect any andorid device throguht PretixSCAN.

When I read QR code with PretixSCAN in Android, my mobile phone says "Security error while trying to reach the server".

Can anyone help me please?

**Comment by raphaelm** [comment]
Can you check if https://www.ssllabs.com/ssltest/analyze.html finds any issues with the SSL configuration of your site?

**Comment by sborja** [comment]
![imagen](https://user-images.githubusercontent.com/5967621/83113594-c9058000-a0bf-11ea-83a0-8f46c649bf4e.png)

This are the results of test...

Can you help me how to identify if i have a problem with ssl connection?

I have a frontenf server with Apache2 that has a proxy pass to each server of our lan, then in pretix server, i have installed a Nginx as documentation says...

**Comment by raphaelm** [comment]
We're not a webserver support here, but if you send full results or domain name I can have a look… The graph alone does not say anything, except that your SSL configuration is really bad. The incomplete certificate chain could be the issue.

Pretty sure the problem is with your Apache server, not pretixscan.

**Comment by sborja** [comment]
Hi, 

Thank you for your help... 

Can you test my domain yourself? 

https://pretix.museoelder.es 



De: "Raphael Michel" <notifications@github.com> 
Para: "pretix/pretixscan-android" <pretixscan-android@noreply.github.com> 
CC: "sborja" <sergio.borja@logican.net>, "Author" <author@noreply.github.com> 
Enviados: Jueves, 28 de Mayo 2020 8:55:56 
Asunto: Re: [pretix/pretixscan-android] Security error while trying to reach the server (#15) 





We're not a webserver support here, but if you send full results or domain name I can have a look… The graph alone does not say anything, except that your SSL configuration is really bad. The incomplete certificate chain could be the issue. 

Pretty sure the problem is with your Apache server, not pretixscan.

**Comment by sborja** [comment]
Hi, 

Thank you for your help... 

Can you test my domain yourself? 

https://pretix.museoelder.es 



Saludos, 

Nota Legal: Este mensaje y sus anexos se dirigen exclusivamente a su destinatario y pueden contener información privada y confidencial para uso exclusivo de su destinatario. Si ha recibido este mensaje por error, le rogamos que nos lo comunique inmediatamente por esta misma vía y proceda a su destrucción, informándole que cualquier divulgación, copia, distribución o uso de los mismos está prohibida en virtud de la legislación vigente. 


Legal Notice: This message and its attachments are exclusively directed to the addressee and may contain private and confidential information for the use of the addressee. If you have received this message by mistake we request that you immediately inform us and delete it. If you are not the intended recipient you are being notified that the coping, disclosing, distribution or use of this information is forbidden by law . 


De: "Raphael Michel" <notifications@github.com> 
Para: "pretix/pretixscan-android" <pretixscan-android@noreply.github.com> 
CC: "sborja" <sergio.borja@logican.net>, "Author" <author@noreply.github.com> 
Enviados: Jueves, 28 de Mayo 2020 8:55:56 
Asunto: Re: [pretix/pretixscan-android] Security error while trying to reach the server (#15) 





We're not a webserver support here, but if you send full results or domain name I can have a look… The graph alone does not say anything, except that your SSL configuration is really bad. The incomplete certificate chain could be the issue. 

Pretty sure the problem is with your Apache server, not pretixscan.

**Comment by raphaelm** [comment]
Yeah, as I guessed, your intermediate certificate is missing, and your SSL settings are horribly insecure in general. Please read up on how to configure Apache2 with SSL. I'm not here as your free Apache support hotline, sorry.

**Comment by sborja** [comment]
Hi again, 

Thank you for your help in advance... 

Now I'm in A state in Qualys but i have same error... I can't add and android device within pretix ("Security error while trying to reach the server"). 

Can you help me with it? 




De: "Raphael Michel" <notifications@github.com> 
Para: "pretix/pretixscan-android" <pretixscan-android@noreply.github.com> 
CC: "sborja" <sergio.borja@logican.net>, "Author" <author@noreply.github.com> 
Enviados: Jueves, 28 de Mayo 2020 9:21:17 
Asunto: Re: [pretix/pretixscan-android] Security error while trying to reach the server (#15) 





Yeah, as I guessed, your intermediate certificate is missing, and your SSL settings are horribly insecure in general. Please read up on how to configure Apache2 with SSL. I'm not here as your free Apache support hotline, sorry.
