### ISSUE TITLE
Kiosk mode. Server error: Permission Denied

### ISSUE THREAD

**Issue by sborja** [pretix/pretixscan-android#24]
Hi,

I have las self-hosted pretix version and i have an error with self-scanning...

I have configured device in pretix platform as Kiosk mode, and eneabled option in PretixSCAN "Automatic Event Selection" and the android device crash with "Server error: Permission Denied".

If i put configuration in pretix platform as "Full Device Access", the system runs right but only in its registry queue... we need to select queue to read QR on its registry queue.

Could anyone help me with this?

Thank you very much.

**Comment by raphaelm** [comment]
Which version of pretix are you using? Can you post the excerpt from your pretix.log file when you get the error?

**Comment by sborja** [comment]
Hi,

We have 3.12 installed and this is error on pretix.log:

WARNING 2020-11-23 10:09:05,378 django.request log Not Found: /api/v1/device/eventselection
WARNING 2020-11-23 10:09:05,378 django.request log Not Found: /api/v1/device/eventselection
WARNING 2020-11-23 10:09:06,532 django.request log Forbidden: /api/v1/organizers/elder/events/EMG/orders/
WARNING 2020-11-23 10:09:06,532 django.request log Forbidden: /api/v1/organizers/elder/events/EMG/orders/
WARNING 2020-11-23 10:09:07,205 django.request log Not Found: /api/v1/device/eventselection
WARNING 2020-11-23 10:09:07,205 django.request log Not Found: /api/v1/device/eventselection
WARNING 2020-11-23 10:09:08,239 django.request log Forbidden: /api/v1/organizers/elder/events/EMG/orders/
WARNING 2020-11-23 10:09:08,239 django.request log Forbidden: /api/v1/organizers/elder/events/EMG/orders/

Thank you for your help...

**Comment by raphaelm** [comment]
Hi,

* On the "Permission denied": If you configure kiosk mode in the pretix platform, you need to turn off "synchronize orders" in the app. This disables offline scanning, basically.

* "Not Found" means the server did not find an event that should be selected next. Is your event at the correct time and date? Is the event "live"? Do you use gates, and if so, is the event's check-in list connected to the right gate?

**Comment by sborja** [comment]
Hi,

. First point is solved, i have unchecked "Download orders" and now sync app correctly.
. With "Not Found" error, We have server timezone in Atlantic/Canary and each event is too in Atlantic/Canary timezone setup. The event that i want to check in with QR code is live, and the event that i have selected in Android, is live too. I don.t use gates at the moment...

This is picture of my app setup:

![WhatsApp Image 2020-11-25 at 08 57 03](https://user-images.githubusercontent.com/5967621/100205371-f1e6c080-2efc-11eb-84a4-a28a03dbe9fd.jpeg)
![WhatsApp Image 2020-11-25 at 08 57 04](https://user-images.githubusercontent.com/5967621/100205375-f27f5700-2efc-11eb-8f45-16cd123c7aaf.jpeg)

Thank you very much...

**Comment by sborja** [comment]
I still have "Not Found" error... and inside Devices Log, this is message:

Unknown scan of code "z5f862d3ruahjmvt…" for list "Entrada", type "entry"

Let me to tell you that we have a registry list called "Entrada" selected on app, and we want to read a QR that owns to another list called "Cita Previa"... 

Thank you very much

**Comment by sborja** [comment]
Hi,

I would appreciate any help with my problem...

Thanks in advance

**Comment by raphaelm** [comment]
I'm sorry, but I did not find the problem at the first attempt, and currently we're pretty busy, I'm not sure I'll be able to spend time to dig deeper on this, as we prioritize support requests from our customers. Maybe someone else finds a solution though.
