### ISSUE TITLE
Check DataWedgeHelper on Android 11

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretixscan-android#37]
I've just needed to upgrade to target SDK 30 to comply with Play Store rules. Target SDK 30 includes scoped storage stuff, which might be a problem for our automated DataWedge profile installation.

@pc-coholic You already have an Android 11 Zebra device, can you wipe DataWedge profiles and see if the new pretixSCAN still automatically reinstalls the DataWedge profile?

If not, can you check if you find out the correct way to adjust it, most likely through an updated path as specified here? https://techdocs.zebra.com/datawedge/11-0/guide/admin/

Worst case we need to switch to the intent API, but it seems that could create problems if other apps want to use DataWedge as well.

**Comment by pc-coholic** [comment]
Wiping datawedge and reinstalling pretixSCAN 1.13.1 will create a new pretix-DW-profile just fine.

I think, we might be okay with what we're doing :)
