### ISSUE TITLE
Support for barcode terminals who send the data as keyboard input

### ISSUE THREAD

**Issue by mvanderkruk** [pretix/pretixscan-android#42]
I have bought a cheap barcode terminal with a 2D scanner. 
This scanner by default sends the scan output as keyboard data followed by an enter.
The PretixScan application however cannot handle this method of input and is omitting the ticket code from the request URL:
Used URL: /api/v1/organizers/GV/events/2020/checkinlists/13/positions/redeem/
Instead of: 
/api/v1/organizers/GV/events/2020/checkinlists/13/positions/rs8a3p67jepqtbt9evz766bfggzhfaqh/redeem/
It would be very nice to have a configuration option to support this way of inputting a ticket code in the PretixScan application.

**Comment by raphaelm** [comment]
This should already be supported, pretixSCAN accepts keyboard input and has been used with USB-attached barcode scanners that emulate a keyboard before.

What kind of device did you buy exactly?

**Comment by mvanderkruk** [comment]
The device is a brandless one. Model number 3501S
https://www.aliexpress.com/item/32954340302.html?gatewayAdapt=glo2nld
The strange thing is, when I use the search function in the app, the ticket code is "typed" in the search field correctly and the ticket is found OK. but this is not useable for bulk ticket scans.
