### ISSUE TITLE
"Mark Ticket automatically as Verified" does not respect "Do not save" option for Covid certificates

### ISSUE THREAD

**Issue by dasGoogle** [pretix/pretixscan-android#44]
When setting the "Do not Save" option in the Covid Certificate Validation Settings and enabling the "Mark Ticket automatically as Verified" option in the Android App settings, the automatically verified certificate is stored in the pretix backend. When a visitor then tries to check in again, there is no new prompt for a certificate, even when "Mark Ticket automatically as Verified" is disabled again.

We would expect the "Mark Ticket automatically as Verified" to not store this information when the setting in the backend is set this way.

**Comment by raphaelm** [comment]
Is there even a valid usecase for combining these options?

**Comment by dasGoogle** [comment]
We have two lists where people are supposed to check in where there is need for certificate validation in only one of them. Both check-ins are supposed to happen with the same ticket. 
Our workaround to achieve this was to set one device to automatically accept while we use another device to check in the other list like normally.

**Comment by dasGoogle** [comment]
For our use we have now built our own version of the app that just sets the value of the covid verification question to an empty string when the "auto-verify"-option is enabled. https://github.com/pretix/pretixscan-android/blob/dab75a545b66ba72469203473091e51ce2b7cc79/pretixscan/app/src/main/java/eu/pretix/pretixscan/droid/ui/MainActivity.kt#L881

This isn't a fix for everyone, but it solves our issue.
So at least we do not need a fix for this anymore at the moment. 

Thanks for creating pretix, we greatly appreciate it!
