### ISSUE TITLE
Offline scanning not working

### ISSUE THREAD

**Issue by mvanderkruk** [pretix/pretixscan-android#49]
When I manually switch to offline scanning, all tickets are reported as "Invalid ticket".
Also switching the device to airplane mode to make the device go into offline mode automatically has the same response: Invalid ticket.
Download orders has been checked, force full sync has been attempted, but no change in the behavior.
Version 2.0.1 has been installed today.

**Comment by mvanderkruk** [comment]
Still the same in the latest version 2.1.0
Every scan is recorded in the ticket history after the device is online again as can be seen in the screenshot below:
![image](https://user-images.githubusercontent.com/2444979/213824740-63c833e7-c515-4709-aa0e-b6248b5ca6b8.png)

**Comment by raphaelm** [comment]
Can you check your server logs (e.g. nginx access log) what URLs are hit by the app exactly when you run a forced full sync?

**Comment by mvanderkruk** [comment]
Hi @raphaelm 
Below is the listing of URL's which are accessed when I run a force full sync

`[IP ADDRESS] - - [23/Jan/2023:23:21:33 +0100] "GET /api/v1/device/info HTTP/1.1" 200 281 "-" "okhttp/4.10.0 eu.pretix.pretixscan.droid/2.1.0"
[IP ADDRESS] - - [23/Jan/2023:23:21:33 +0100] "GET /api/v1/organizers/GV/subevents/ HTTP/1.1" 200 52 "-" "okhttp/4.10.0 eu.pretix.pretixscan.droid/2.1.0"
[IP ADDRESS] - - [23/Jan/2023:23:21:35 +0100] "GET /api/v1/organizers/GV/events/2020/ HTTP/1.1" 200 811 "-" "okhttp/4.10.0 eu.pretix.pretixscan.droid/2.1.0"
[IP ADDRESS] - - [23/Jan/2023:23:21:36 +0100] "GET /api/v1/organizers/GV/events/2020/categories/ HTTP/1.1" 200 793 "-" "okhttp/4.10.0 eu.pretix.pretixscan.droid/2.1.0"
[IP ADDRESS] - - [23/Jan/2023:23:21:38 +0100] "GET /api/v1/organizers/GV/events/2020/items/ HTTP/1.1" 200 17117 "-" "okhttp/4.10.0 eu.pretix.pretixscan.droid/2.1.0"
[IP ADDRESS] - - [23/Jan/2023:23:21:41 +0100] "GET /api/v1/organizers/GV/events/2020/questions/ HTTP/1.1" 200 1890 "-" "okhttp/4.10.0 eu.pretix.pretixscan.droid/2.1.0"
[IP ADDRESS] - - [23/Jan/2023:23:21:42 +0100] "GET /api/v1/organizers/GV/events/2020/badgelayouts/ HTTP/1.1" 200 52 "-" "okhttp/4.10.0 eu.pretix.pretixscan.droid/2.1.0"
[IP ADDRESS] - - [23/Jan/2023:23:21:42 +0100] "GET /api/v1/organizers/GV/events/2020/badgeitems/ HTTP/1.1" 200 52 "-" "okhttp/4.10.0 eu.pretix.pretixscan.droid/2.1.0"
[IP ADDRESS] - - [23/Jan/2023:23:21:42 +0100] "GET /api/v1/organizers/GV/events/2020/checkinlists/?exclude=checkin_count&exclude=position_count HTTP/1.1" 200 948 "-" "okhttp/4.10.0 eu.pretix.pretixscan.droid/2.1.0"
[IP ADDRESS] - - [23/Jan/2023:23:21:44 +0100] "GET /api/v1/organizers/GV/events/2020/revokedsecrets/ HTTP/1.1" 200 52 "-" "okhttp/4.10.0 eu.pretix.pretixscan.droid/2.1.0"
[IP ADDRESS] - - [23/Jan/2023:23:21:44 +0100] "GET /api/v1/organizers/GV/events/2020/orders/?testmode=false&exclude=downloads&exclude=payment_date&exclude=payment_provider&exclude=fees&exclude=positions.downloads&exclude=payments&exclude=refunds HTTP/1.1" 200 52 "-" "okhttp/4.10.0 eu.pretix.pretixscan.droid/2.1.0"
[IP ADDRESS] - - [23/Jan/2023:23:21:46 +0100] "GET /api/v1/organizers/GV/events/2020/settings/ HTTP/1.1" 200 1215 "-" "okhttp/4.10.0 eu.pretix.pretixscan.droid/2.1.0"
`

The Source IP is redacted from the logs.

**Comment by raphaelm** [comment]
This is the relevant line:
```
[23/Jan/2023:23:21:44 +0100] "GET /api/v1/organizers/GV/events/2020/orders/?testmode=false&exclude=downloads&exclude=payment_date&exclude=payment_provider&exclude=fees&exclude=positions.downloads&exclude=payments&exclude=refunds HTTP/1.1" 200 52 "-" "okhttp/4.10.0 eu.pretix.pretixscan.droid/2.1.0"
```

"52 bytes" sounds like an empty response. For some reason, the server does not return any orders to this request.

Could it be, that you only have orders in "test mode"? These are not synced on purpose.

**Comment by mvanderkruk** [comment]
You are correct, the shop I use to test was in test mode. When in live mode the orders are synced and tickets are checked offline. 
Might be useful to add this in the documentation somewhere.
