### ISSUE TITLE
javax.crypto.BadPaddingException

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretixscan-android#5]
Apparently, on Android Q beta, the app crashes with

```
Unable to start activity ComponentInfo{eu.pretix.pretixscan.droid/eu.pretix.pretixscan.droid.ui.MainActivity}: java.lang.RuntimeException: javax.crypto.BadPaddingException
```

@pc-coholic since you are apparently running the beta anyways, would you care to take a deeper look at this or shall I? pretixPOS might be affected as well.

**Comment by pc-coholic** [comment]
I can have a look when my phone is back from the repair shop... Should be within the next two weeks or so :)

**Comment by raphaelm** [comment]
That should be enough :D

**Comment by pc-coholic** [comment]
This issue might be resolved with the latest Android Q release, as the emulator does not throw any errors. Will have to test this again with a proper device in hand.

**Comment by raphaelm** [comment]
Seems to be fixed.

**Comment by raphaelm** [comment]
see https://twitter.com/techniker/status/1301225642130894849

**Comment by raphaelm** [comment]
@techniker Can you tell us when exactly this happens? Before or after you connected the app to pretix?

**Comment by techniker** [comment]
@raphaelm After a fresh Android 10 install (factory, enterprise reset) on a Zebra TC26 (Wifi+LTE, 4GB RAM, 64GB eMMC) the App crashes after every single try to open it.

**Comment by raphaelm** [comment]
So the crash happens here:

https://github.com/pretix/pretixscan-android/blob/84008e24c1722a51ec361c80e3909e64876301fa/pretixscan/app/src/main/java/eu/pretix/pretixscan/droid/AppConfig.kt#L94

My suspicion is that it crashes when ``prefs.getString(PREFS_KEY_API_KEY, "") == ""``, which is obviously not a value that we should try to decrypt. I haven't verified this theory yet, but it would every much fit the error message.

The weird thing is that the stacktrace on twitter points to the call here:

https://github.com/pretix/pretixscan-android/blob/84008e24c1722a51ec361c80e3909e64876301fa/pretixscan/app/src/main/java/eu/pretix/pretixscan/droid/ui/MainActivity.kt#L346

Which shouldn't be called before the app is set up, since the function returns two lines above in this case.

**Comment by pc-coholic** [comment]
I'm still having trouble reproducing this with my TC26 (which is the exact same model as you have)...

So far, I've always used the Android-native Factory Reset from the Settings... When you're saying `factory, enterprise reset`: Are you using the factory/enterprise-reset-files provided by Zebra? If so, which ones and in which order?

**Comment by techniker** [comment]
@pc-coholic Yes, they are the files provided by Zebra. First Factory then Enterprise package.

**Comment by raphaelm** [comment]
So we've acquired a few TC26s to reproduce this ;) and so far I haven't seen it.

We must be missing some detail here that is not the Android version.

![IMG_20201021_170447.jpg](https://user-images.githubusercontent.com/64280/96739010-9e45fc00-13bf-11eb-9fcc-472f7035ea55.jpg)

**Comment by raphaelm** [comment]
So I've spent some more time on this. First of all, we've seen hundreds of reports on this through our error reporting, and the error seems entirely unrelated to device or Android version.

With one client, we've been able to narrow it down to this:

* Client uninstalls app
* Client installs app again
* Google Play restores the app's settings from cloud backup
* The app's settings contain the encrypted API Key, however since the keystore is not part of cloud backup, it can't be decrypted, leading to the error reported here
* Verification: After a manual app data wipe in settings everything is fine again

With 8fcfc75f6cca91640b04671958e01e6981a1a501 we've disabled ``allowBackup`` since it is pointless anyways if restore is impossible. With cb1c8e1b19adbb4819438d5bb1784c6f7081ad5a we've added auto-detection of this situation and will reset the config in that case.

So if anyone still is able to reproduce this on a newer version than 1.10.5, please re-open the issue. If possible for you, please mail us the actual device for some testing (after prior contact please).

I believe this might *also* happen if you upgrade a device from Android 4.x or 5.x to 6.x or newer. However, since most old devices don't receive updates and a reinstall will fix it, I don't think we'll spend effort on that.
