### ISSUE TITLE
Automatically select check-in list if there is only one

### ISSUE THREAD

**Issue by DerDakon** [pretix/pretixscan-android#61]
If the event only has a single check-in list then just use this without additional confirmation.

**Comment by raphaelm** [comment]
Hmm, that could also be very confusing in some cases

**Comment by DerDakon** [comment]
Maybe with a checkbox to allow the user to enable or disable this behavior?

**Comment by raphaelm** [comment]
No, I don't think we'd introduce a setting for this.

**Comment by joelebeau9** [comment]
+1 for this - there are too many unnecessary clicks between selecting an event and scanning
