### ISSUE TITLE
cannot connect my device to pretixScan

### ISSUE THREAD

**Issue by alemao8** [pretix/pretixscan-android#64]
Hello pretix team.

I am trying to configure pretixscan on my android device in order to use for check-in.
I am trying to connect my device in the Devices section of organizer account in the pretix backend, but I am getting the message
"Security error while trying to reach the server." This happens when using the QR code that is generated and even if I use the manual setup and enter the System URL and Token.

Thank you in advance.

**Comment by raphaelm** [comment]
Can you check if https://www.ssllabs.com/ssltest/analyze.html shows any warnings for your domain such as a broken certificate chain?

**Comment by fabianhugo** [comment]
Hello, 
i had the same problem.The SSL check did not show an issue in the certificate chain. In the end it was a missing https: in the url in the pretix.cfg config file. It is minor, but maybe it helps someone.

**Comment by alemao8** [comment]
My issue was with the chain of the SSL. A great help with https://whatsmychaincert.com.
