### ISSUE TITLE
No value passed for parameter 'allAnswersAreOptional'

### ISSUE THREAD

**Issue by i43kje** [pretix/pretixscan-android#69]
Hi, when opening project through android studio VCS I am unable to get project to work and get the following error -

e: /Users/dev/StudioProjects/pretixscan-android/pretixscan/libpretixui-repo/libpretixui-android/src/main/java/eu/pretix/libpretixui/android/questions/QuestionsDialog.kt: (670, 65): No value passed for parameter 'p2'

**Comment by raphaelm** [comment]
Have you updated all submodules to their latest version?
