### ISSUE TITLE
Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by SrLucca** [pretix/pretixscan-android#83]
Anyone can help me? Im having that error when im trying to build project on android studio

e.g: Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not GET 'https://maven.pkg.github.com/Digitaler-Impfnachweis/covpass-android/com/ibm/health/de/rki/covpass/covpass-sdk/1.552.1/covpass-sdk-1.552.1.pom'. Received status code 401 from server: Unauthorized

**Comment by pc-coholic** [comment]
You'll need to add an entry called `github.token` to your `local.properties` with a Personal GitHub Access token, which has been granted the `read:packages` permission.
