### ISSUE TITLE
Typo in sentry config filename

### ISSUE THREAD

**Issue by Centzilius** [pretix/pretixscan-android#89]
Hi,
I just noticed that there is a file called `setnry.properties` that has been added with the initial commit of this repository.

https://github.com/pretix/pretixscan-android/blob/master/pretixscan/setnry.properties

https://github.com/pretix/pretixscan-android/blob/master/BUILDING.md seems to suggest that local.properties is to be used so it might be fine to just delete that file?

**Comment by robbi5** [comment]
Yep, you're right. Thanks :)
